# Configure PostgreSQL connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.http.port=8081

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/employee_db

# Automatically create or update database tables based on entities
quarkus.hibernate-orm.database.generation=update